categories:
  - name: gaming
    title: "🎮 News in Vidya"
    accounts:
      - Okami13_
      - Wario64
      - BoLSNEWS

  - name: drama
    title: "📣 The Skinny"
    accounts:
      - DramaAlert
      - Awk20000