name: Daily Discord Digest

on:
  schedule:
    - cron: "0 16 * * *"  # 11 AM CT / 12 PM ET / 16:00 UTC
  workflow_dispatch:

jobs:
  post-digest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run news digest
        run: python news_to_discord.py
        env:
          X_BEARER_TOKEN: ${{ secrets.X_BEARER_TOKEN }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
